"use client";

import React from "react";
import { motion } from "framer-motion";
import { TargetMarket, Industry, ReadinessResult } from "@/lib/readinessScore";
import { ScoreGauge } from "@/components/ui/ScoreGauge";
import {
  Sparkles,
  RotateCcw,
  Globe2,
  ShieldCheck,
  Landmark,
  TrendingUp,
  CheckCircle2,
} from "lucide-react";

interface StepProfileSnapshotProps {
  userName?: string;
  companyName?: string;
  isExistingCustomer?: boolean | null;
  selectedMarket?: TargetMarket | null;
  selectedIndustry?: Industry | null;
  readinessResult: ReadinessResult | null;
  onRestart: () => void;
}

export const StepProfileSnapshot: React.FC<StepProfileSnapshotProps> = ({
  userName = "Exporter",
  companyName,
  isExistingCustomer,
  selectedMarket,
  selectedIndustry,
  readinessResult,
  onRestart,
}) => {
  const resolvedMarket: TargetMarket = selectedMarket || "United Kingdom";
  const resolvedIndustry: Industry = selectedIndustry || "Textiles & Apparel";
  const score = readinessResult?.overallScore || 78;
  const complexity = readinessResult?.regulatoryComplexity || "Low";
  const scoreBand = readinessResult?.scoreBand || "High Readiness";

  const getCorridorFlag = (market: TargetMarket) => {
    switch (market) {
      case "United Kingdom":
        return "🇬🇧";
      case "United States":
        return "🇺🇸";
      case "UAE":
        return "🇦🇪";
      case "Singapore":
        return "🇸🇬";
      case "Germany":
        return "🇩🇪";
      default:
        return "🌐";
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto flex flex-col items-center justify-center px-4 py-8 sm:py-12 text-center">
      {/* Top Badge */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-black/5 border border-black/10 mb-4"
      >
        <Sparkles className="h-3.5 w-3.5 text-[#FF4D1C]" />
        <span className="font-mono-data text-xs uppercase tracking-widest font-semibold text-[#0A0A0A]">
          TRADEPE CLIENT PORTFOLIO SNAPSHOT
        </span>
      </motion.div>

      {/* Personalized Header */}
      <motion.h1
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="font-display font-bold text-4xl sm:text-5xl md:text-6xl text-[#0A0A0A] tracking-tight leading-[1.08] mb-3"
      >
        {userName}&apos;s Market Access Profile
      </motion.h1>

      {companyName && (
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.15 }}
          className="font-mono-data text-xs sm:text-sm uppercase tracking-wider text-[#FF4D1C] font-semibold mb-8"
        >
          {companyName} • DIRECT-CLEARING PROFILE
        </motion.p>
      )}

      {!companyName && (
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.15 }}
          className="font-body text-base sm:text-lg text-[#706E6B] font-light mb-8 max-w-lg"
        >
          Verified global corridor blueprint generated by Market Access Desk.
        </motion.p>
      )}

      {/* Summary Matrix Cards */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="w-full grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mb-8 text-left"
      >
        {/* Card 1: Expansion Corridor */}
        <div className="p-6 rounded-2xl bg-white border-2 border-black/10 shadow-sm flex flex-col justify-between">
          <div className="flex items-center gap-2 text-[#706E6B] mb-2">
            <Globe2 className="h-4 w-4 text-[#FF4D1C]" />
            <span className="font-mono-data text-[11px] uppercase tracking-wider font-semibold">
              Corridor Target
            </span>
          </div>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-2xl"></span>
              <span className="font-display font-bold text-xl text-[#0A0A0A]">
                {resolvedMarket}
              </span>
            </div>
            <span className="font-body text-xs text-[#706E6B]">
              Sector: {resolvedIndustry}
            </span>
          </div>
        </div>

        {/* Card 2: Readiness Index */}
        <div className="p-6 rounded-2xl bg-white border-2 border-black/10 shadow-sm flex flex-col justify-between">
          <div className="flex items-center gap-2 text-[#706E6B] mb-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-600" />
            <span className="font-mono-data text-[11px] uppercase tracking-wider font-semibold">
              Readiness Score
            </span>
          </div>
          <div>
            <div className="flex items-baseline gap-2 mb-1">
              <span className="font-mono-data text-4xl sm:text-5xl font-bold text-[#0A0A0A] tracking-tight">
                {score}
              </span>
              <span className="font-mono-data text-xs text-[#706E6B]">/ 100</span>
            </div>
            <span className="font-mono-data text-[11px] uppercase font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded">
              {scoreBand}
            </span>
          </div>
        </div>

        {/* Card 3: Regulatory Friction */}
        <div className="p-6 rounded-2xl bg-white border-2 border-black/10 shadow-sm flex flex-col justify-between">
          <div className="flex items-center gap-2 text-[#706E6B] mb-2">
            <ShieldCheck className="h-4 w-4 text-[#0A0A0A]" />
            <span className="font-mono-data text-[11px] uppercase tracking-wider font-semibold">
              Compliance Level
            </span>
          </div>
          <div>
            <span className="font-mono-data text-2xl sm:text-3xl font-bold text-[#0A0A0A] block mb-1">
              {complexity} Friction
            </span>
            <span className="font-body text-xs text-[#706E6B]">
              4 Mandatory filings pre-mapped
            </span>
          </div>
        </div>
      </motion.div>

      {/* Existing Customer Telemetry Highlight (If applicable) */}
      {isExistingCustomer && (
        <motion.div
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.25 }}
          className="w-full p-6 sm:p-7 rounded-2xl bg-white border-2 border-black/10 shadow-sm mb-8 text-left"
        >
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-[#FF4D1C]" />
              <span className="font-display font-bold text-lg sm:text-xl text-[#0A0A0A]">
                Active TradePe Direct-Clearing Telemetry
              </span>
            </div>
            <span className="font-mono-data text-xs uppercase font-semibold px-2.5 py-0.5 rounded-full bg-emerald-50 text-emerald-700">
              Live Feed
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="p-3.5 rounded-xl bg-black/[0.03]">
              <span className="font-mono-data text-[11px] text-[#706E6B] block mb-1">
                QUARTERLY RUN-RATE
              </span>
              <span className="font-mono-data text-2xl font-bold text-emerald-700">
                +40.2% Growth
              </span>
            </div>
            <div className="p-3.5 rounded-xl bg-black/[0.03]">
              <span className="font-mono-data text-[11px] text-[#706E6B] block mb-1">
                AVG CLEARING SPEED
              </span>
              <span className="font-mono-data text-2xl font-bold text-[#0A0A0A]">
                4.2 Hours
              </span>
            </div>
            <div className="p-3.5 rounded-xl bg-black/[0.03]">
              <span className="font-mono-data text-[11px] text-[#706E6B] block mb-1">
                PEER EXPANSION MATCH
              </span>
              <span className="font-mono-data text-2xl font-bold text-[#FF4D1C]">
                Germany (94%)
              </span>
            </div>
          </div>
        </motion.div>
      )}

      {/* Brand Closing Line */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, delay: 0.3 }}
        className="my-6 max-w-xl"
      >
      </motion.div>

      {/* Single Final Action Button */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.35 }}
        className="w-full sm:w-auto min-w-[280px]"
      >
        <button
          type="button"
          onClick={onRestart}
          className="w-full group flex items-center justify-center gap-2.5 py-4 px-8 rounded-xl bg-[#0A0A0A] text-white font-display font-semibold text-lg border-2 border-[#0A0A0A] hover:border-[#FF4D1C] shadow-sm hover:shadow-card transition-all duration-200 hover:-translate-y-0.5"
        >
          <RotateCcw className="h-5 w-5 text-white/70 group-hover:text-white group-hover:-rotate-90 transition-transform duration-300" />
          <span>Restart Demo</span>
        </button>
      </motion.div>
    </div>
  );
};
